server.servlet.context-path=/bsacoretest
server.port=4270

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bsagroup_admin_test?serverTimezone=Asia/Kolkata
spring.datasource.username=bsagroup_admin_test
spring.datasource.password=@dmin123


server.ssl.key-store=/home/bsagroup/keystore.p12
server.ssl.key-store-password=@dmin123
server.ssl.key-store-type=PKCS12

upload.directory=/uploads/test/media/adminbackend/inventory/
upload.exclusivedirectory=/uploads/test/media/adminbackend/exclusiveproduct/

spring.servlet.multipart.max-file-size=20MB

app.jwtExpirationInMs=3600000