server.servlet.context-path=/bsacore
server.port=3270

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bsagroup_admin_prod?serverTimezone=Asia/Kolkata
spring.datasource.username=bsagroup_admin_prod
spring.datasource.password=@dmin123


server.ssl.key-store=/home/bsagroup/keystore.p12
server.ssl.key-store-password=@dmin123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=alias1

upload.directory=/uploads/prod/media/adminbackend/inventory/
upload.exclusivedirectory=/uploads/prod/media/adminbackend/exclusiveproduct/

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


app.jwtExpirationInMs=3600000