spring.profiles.active =dev
spring.application.name=bsaadmin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
app.jwtSecret=8e41b3242105dac820238e6e4dc6c193edd1e5fdada5764c60c1168578855e41af6eda08d5862476a84d7aa4603630eeaf03a751586ddaa602d3517593ab3c38

spring.jackson.time-zone=Asia/Kolkata
